/**
 * Amenity icon artwork.
 *
 * Hand-authored line icons drawn on a 24 grid to a single visual language:
 * ~1.5px stroke, rounded caps and joins, monochrome, colour inherited from
 * `currentColor`. They are original drawings, not traced artwork and not an
 * icon pack — generic packs carry their own proportions and read as foreign
 * next to the rest of the page.
 *
 * `SHAPES` holds one entry per distinct drawing. `AMENITY_SHAPE` maps each
 * amenity id onto one of them, so the several amenities that legitimately
 * share a pictogram (fridge/freezer, kitchen/cooking basics, the two
 * entrance rows) reuse a single drawing instead of duplicating path data.
 * `AmenityIcon` supplies the wrapper.
 */
export interface IconPath {
  d: string;
  /** Filled rather than stroked. Defaults to stroked. */
  fill?: boolean;
}

const SHAPES = {
  'air-conditioning': [
    { d: 'M12 3.5v17' },
    { d: 'M4.6 7.8 19.4 16.2' },
    { d: 'M19.4 7.8 4.6 16.2' },
    { d: 'M12 3.5 9.8 6M12 3.5l2.2 2.5' },
    { d: 'M12 20.5 9.8 18M12 20.5l2.2-2.5' },
  ],
  'bed-linen': [
    { d: 'M5 3.5h9l5 5v12H5z' },
    { d: 'M14 3.5v5h5' },
    { d: 'M5 17.5c2-1.4 4-1.4 6 0' },
  ],
  blender: [
    { d: 'M7 3.5h10l-1.5 8h-7Z' },
    { d: 'M10 11.5h4v5h-4z' },
    { d: 'M7.5 16.5h9v4h-9z' },
  ],
  blinds: [
    { d: 'M4 4h16' },
    { d: 'M5 4v10h14V4' },
    { d: 'M12 14v5' },
    { d: 'M10.5 19.5h3' },
  ],
  camera: [
    { d: 'M3 8.5 16 5l1.6 5.6L4.6 14 3 8.5Z' },
    { d: 'M6 14v6M17.6 10.6 21 9.7' },
  ],
  /* Both alarm rows render "not reported" on this listing, so each carries a
     struck-through glyph rather than a plain alarm. */
  'co-alarm': [{ d: 'M4 4h16v16H4z' }, { d: 'M4 4l16 16' }],
  'smoke-alarm': [{ d: 'M12 4a8 8 0 1 0 0 16 8 8 0 0 0 0-16Z' }, { d: 'M4 4l16 16' }],
  'cleaning-products': [
    { d: 'M9 8h5v13H9z' },
    { d: 'M10.5 8V4.5h3V8' },
    { d: 'M14 6h3.5v3' },
    { d: 'M9 12.5h5' },
  ],
  'clothes-storage': [
    { d: 'M4 3.5h16v16H4z' },
    { d: 'M12 3.5v16' },
    { d: 'M9.5 10.5v2M14.5 10.5v2' },
    { d: 'M6 19.5v1.5M18 19.5v1.5' },
  ],
  coffee: [
    { d: 'M5 4.5h13v4H5z' },
    { d: 'M6.5 8.5v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2v-9' },
    { d: 'M8.5 11.5h6' },
    { d: 'M18 6h2.5v4H18' },
  ],
  cooker: [
    { d: 'M4.5 4.5h15v15h-15z' },
    {
      d:
        'M9 9a1.4 1.4 0 1 0 0 2.8A1.4 1.4 0 0 0 9 9Zm6 0a1.4 1.4 0 1 0 0 2.8A1.4 1.4 0 0 0 15 9Z' +
        'M9 14a1.4 1.4 0 1 0 0 2.8A1.4 1.4 0 0 0 9 14Zm6 0a1.4 1.4 0 1 0 0 2.8A1.4 1.4 0 0 0 15 14Z',
    },
  ],
  cot: [
    { d: 'M3.5 7v11M20.5 7v11' },
    { d: 'M3.5 9h17' },
    { d: 'M7 9v7M10.5 9v7M14 9v7M17.5 9v7' },
  ],
  crockery: [
    { d: 'M6 3.5v8a2 2 0 0 0 4 0v-8' },
    { d: 'M8 11.5V21' },
    { d: 'M17 3.5c-1.6 1.4-2.4 3.4-2.4 6 0 1.7.6 3 1.7 3.7V21' },
  ],
  /* A door in its frame, jamb drawn separately — used by both the
     private-entrance and self-check-in rows. */
  door: [
    { d: 'M5.2 3.4h9.6v17.2H5.2Z' },
    { d: 'M17 3.4v17.2' },
    { d: 'M12.6 12.2h.01' },
    { d: 'M3.2 20.8h17.6' },
  ],
  /* Four blades evenly spaced about a small hub, generated by rotating one
     petal; three partial shapes read as a squiggle at 24px. */
  fan: [
    { d: 'M11.6 11C11.2 7.7 12 3.9 14.8 3.2C17.7 2.6 17.8 6 15.9 7.9C14.2 9.6 12.7 10.6 11.6 11Z' },
    { d: 'M11.6 11C14.9 10.6 18.7 11.4 19.4 14.2C20 17.1 16.6 17.2 14.7 15.3C13 13.6 12 12.1 11.6 11Z' },
    { d: 'M11.6 11C12 14.3 11.2 18.1 8.4 18.8C5.5 19.4 5.4 16 7.3 14.1C9 12.4 10.5 11.4 11.6 11Z' },
    { d: 'M11.6 11C8.3 11.4 4.5 10.6 3.8 7.8C3.2 4.9 6.6 4.8 8.5 6.7C10.2 8.4 11.2 9.9 11.6 11Z' },
    { d: 'M11.6 9.8a1.2 1.2 0 1 0 0 2.4 1.2 1.2 0 0 0 0-2.4Z' },
  ],
  fridge: [
    { d: 'M5.5 3.5h13v17h-13z' },
    { d: 'M5.5 10h13' },
    { d: 'M8 6.5v2M8 13v2.5' },
  ],
  gym: [{ d: 'M3 9.5v5M6 7.5v9M18 7.5v9M21 9.5v5' }, { d: 'M6 12h12' }],
  hairdryer: [
    { d: 'M3 8.5h9.5a4 4 0 0 1 0 8H9l-1 4.5H5l1-4.5H3a2.5 2.5 0 0 1 0-8Z' },
    { d: 'M13 12.5h7' },
  ],
  hangers: [
    { d: 'M12 7.2a1.8 1.8 0 1 1 1.8-1.8' },
    { d: 'M12 7.2 3.5 14a1 1 0 0 0 .6 1.8h15.8a1 1 0 0 0 .6-1.8L12 7.2Z' },
  ],
  'hot-tub': [
    { d: 'M4 12h16v4a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4v-4Z' },
    { d: 'M8 9c0-1.5 1-2 1-3.5' },
    { d: 'M12 9c0-1.5 1-2 1-3.5' },
    { d: 'M16 9c0-1.5 1-2 1-3.5' },
  ],
  'hot-water': [
    { d: 'M4 12h16v4.5a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4V12Z' },
    { d: 'M9 9c0-1.4 1-1.8 1-3.2' },
    { d: 'M13 9c0-1.4 1-1.8 1-3.2' },
    { d: 'M17 9c0-1.4 1-1.8 1-3.2' },
  ],
  iron: [
    { d: 'M3.5 16.5c0-4 3.4-6.5 7.5-6.5h9.5v6.5H3.5Z' },
    { d: 'M15 10V7.5h-6' },
  ],
  kettle: [
    { d: 'M6 9.5h10a4 4 0 0 1 4 4v3a4 4 0 0 1-4 4H10a4 4 0 0 1-4-4v-7Z' },
    { d: 'M6 12H4a1.5 1.5 0 0 1 0-3h2' },
    { d: 'M9.5 9.5 11 5.5h4l1.5 4' },
  ],
  /* A pan and a whisk — carries both the kitchen and cooking-basics rows. */
  kitchen: [
    { d: 'M7 3v8M5 3v4a2 2 0 0 0 4 0V3M7 11v10' },
    { d: 'M17 3c-1.7 1.4-2.5 3.4-2.5 6 0 1.7.6 3 1.7 3.7V21' },
  ],
  'long-term': [
    { d: 'M4 5.5h16v15H4z' },
    { d: 'M4 9.5h16' },
    { d: 'M8 3v4M16 3v4' },
    { d: 'M16.5 20.5 20 17v3.5Z' },
  ],
  microwave: [
    { d: 'M3 5.5h18v13H3z' },
    { d: 'M6 8.5h9v7H6z' },
    { d: 'M18 9h.01M18 12h.01' },
  ],
  'outdoor-dining': [
    { d: 'M3.5 10.5 12 4l8.5 6.5Z' },
    { d: 'M6 10.5v9M18 10.5v9' },
    { d: 'M6 14.5h12' },
    { d: 'M10 14.5v5M14 14.5v5' },
  ],
  parking: [
    { d: 'M5 17v-4.5l1.8-4A2 2 0 0 1 8.6 7h6.8a2 2 0 0 1 1.8 1.5l1.8 4V17' },
    { d: 'M5 17h14M7 17v2M17 17v2M7.5 13h9' },
  ],
  patio: [
    { d: 'M12 3.5a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z' },
    { d: 'M12 11.5v9' },
    { d: 'M12 15.5 8.5 13M12 15.5l3.5-2.5' },
  ],
  pets: [
    { d: 'M6.5 11a1.8 1.8 0 1 0 0-3.6 1.8 1.8 0 0 0 0 3.6Z' },
    { d: 'M17.5 11a1.8 1.8 0 1 0 0-3.6 1.8 1.8 0 0 0 0 3.6Z' },
    { d: 'M9.8 7.4a1.7 1.7 0 1 0 0-3.4 1.7 1.7 0 0 0 0 3.4Z' },
    { d: 'M14.2 7.4a1.7 1.7 0 1 0 0-3.4 1.7 1.7 0 0 0 0 3.4Z' },
    { d: 'M12 12c2.4 0 4.4 1.8 4.4 4 0 1.6-1.2 2.6-2.7 2.6-1 0-1.2-.4-1.7-.4s-.7.4-1.7.4c-1.5 0-2.7-1-2.7-2.6 0-2.2 2-4 4.4-4Z' },
  ],
  pool: [
    { d: 'M3 17c1.5 0 1.5 1.2 3 1.2S7.5 17 9 17s1.5 1.2 3 1.2S13.5 17 15 17s1.5 1.2 3 1.2S19.5 17 21 17' },
    { d: 'M8 15V6a2 2 0 0 1 4 0M16 15V6a2 2 0 0 0-4 0' },
    { d: 'M8 10h8' },
  ],
  shampoo: [{ d: 'M9 9h5v12H9z' }, { d: 'M10.5 9V6h2v3' }, { d: 'M10 3.5h3' }],
  'shower-gel': [
    { d: 'M9 9.5h4.5V21H9z' },
    { d: 'M10.5 9.5V6h2v3.5' },
    { d: 'M16 7h.01M18 10h.01M16.5 13h.01' },
  ],
  toaster: [
    { d: 'M4 9.5a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2Z' },
    { d: 'M8 7.5V5.5M16 7.5V5.5' },
    { d: 'M17 13h1.5' },
  ],
  tv: [{ d: 'M3.5 5h17v11h-17z' }, { d: 'M9 20h6' }, { d: 'M12 16v4' }],
  'washing-machine': [
    { d: 'M4 3.5h16v17H4z' },
    { d: 'M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Z' },
    { d: 'M7 6h.01M10 6h.01' },
  ],
  wifi: [
    { d: 'M2.5 9.5a14 14 0 0 1 19 0' },
    { d: 'M6 13a9 9 0 0 1 12 0' },
    { d: 'M9.5 16.5a4 4 0 0 1 5 0' },
    { d: 'M12 20h.01' },
  ],
  'wine-glasses': [
    { d: 'M7 3.5h10l-.8 6a4.2 4.2 0 0 1-8.4 0Z' },
    { d: 'M12 13.5v6' },
    { d: 'M8.5 20.5h7' },
  ],
  workspace: [{ d: 'M4 17h16M6 17V9h12v8M9 9V6h6v3M4 21h16' }],
} satisfies Record<string, readonly IconPath[]>;

/** Every drawing `AMENITY_SHAPE` is allowed to point at. */
type ShapeName = keyof typeof SHAPES;

/** Amenity id → the drawing in `SHAPES` it renders. */
const AMENITY_SHAPE: Readonly<Record<string, ShapeName>> = {
  'air-conditioning': 'air-conditioning',
  'bed-linen': 'bed-linen',
  blender: 'blender',
  'carbon-monoxide-alarm': 'co-alarm',
  'ceiling-fan': 'fan',
  'cleaning-available-during-stay': 'cleaning-products',
  'cleaning-products': 'cleaning-products',
  'clothes-storage': 'clothes-storage',
  coffee: 'coffee',
  cooker: 'cooker',
  'cooking-basics': 'kitchen',
  cot: 'cot',
  'crockery-and-cutlery': 'crockery',
  'dedicated-workspace': 'workspace',
  'exterior-security-cameras-on-property': 'camera',
  'free-parking-on-premises': 'parking',
  freezer: 'fridge',
  fridge: 'fridge',
  gym: 'gym',
  hairdryer: 'hairdryer',
  hangers: 'hangers',
  'hot-tub': 'hot-tub',
  'hot-water': 'hot-water',
  iron: 'iron',
  kettle: 'kettle',
  kitchen: 'kitchen',
  'long-term-stays-allowed': 'long-term',
  microwave: 'microwave',
  'outdoor-dining-area': 'outdoor-dining',
  'patio-or-balcony': 'patio',
  'pets-allowed': 'pets',
  pool: 'pool',
  'private-entrance': 'door',
  'room-darkening-blinds': 'blinds',
  'self-check-in': 'door',
  shampoo: 'shampoo',
  'shower-gel': 'shower-gel',
  'smoke-alarm': 'smoke-alarm',
  tv: 'tv',
  toaster: 'toaster',
  'washing-machine': 'washing-machine',
  wifi: 'wifi',
  'wine-glasses': 'wine-glasses',
};

export const AMENITY_ICON_PATHS: Readonly<Record<string, readonly IconPath[]>> =
  Object.fromEntries(
    Object.entries(AMENITY_SHAPE).map(([amenityId, shape]) => [amenityId, SHAPES[shape]]),
  );
